#include <Mini2D/Mini2D.hpp>
#include <Mini2D/Image.hpp>
#include <Mini2D/Units.hpp>

Image * tex_bgimg;
Image * tex_cheat;
Image * tex_circle_error_dark;
Image * tex_circle_error_light;
Image * tex_circle_loading_bg;
Image * tex_circle_loading_seek;
Image * tex_edit_ico_add;
Image * tex_edit_ico_del;
Image * tex_edit_shadow;
Image * tex_footer_ico_circle;
Image * tex_footer_ico_cross;
Image * tex_footer_ico_lt;
Image * tex_footer_ico_rt;
Image * tex_footer_ico_square;
Image * tex_footer_ico_triangle;
Image * tex_header_dot;
Image * tex_header_ico_abt;
Image * tex_header_ico_cht;
Image * tex_header_ico_opt;
Image * tex_header_ico_xmb;
Image * tex_header_line;
Image * tex_help;
Image * tex_mark_arrow;
Image * tex_mark_line;
Image * tex_opt_off;
Image * tex_opt_on;
Image * tex_scroll_bg;
Image * tex_scroll_lock;
Image * tex_titlescr_ico_abt;
Image * tex_titlescr_ico_cht;
Image * tex_titlescr_ico_opt;
Image * tex_titlescr_ico_xmb;
Image * tex_titlescr_logo;

Vector2 CENTER_LOC =					Vector2(0.5, 0.5);
Vector2 FULL_DIM =						Vector2(1.0, 1.0);
Vector2 TEX_BGIMG_LOC = 				CENTER_LOC;
Vector2 TEX_BGIMG_DIM = 				FULL_DIM;
Vector2 TEX_CHEAT_LOC = 				CENTER_LOC;
Vector2 TEX_CHEAT_DIM = 				FULL_DIM;
Vector2 TEX_CIRCLE_ERROR_DARK_LOC = 	CENTER_LOC;
Vector2 TEX_CIRCLE_ERROR_DARK_DIM = 	FULL_DIM;
Vector2 TEX_CIRCLE_ERROR_LIGHT_LOC = 	CENTER_LOC;
Vector2 TEX_CIRCLE_ERROR_LIGHT_DIM = 	FULL_DIM;
Vector2 TEX_CIRCLE_LOADING_BG_LOC = 	CENTER_LOC;
Vector2 TEX_CIRCLE_LOADING_BG_DIM = 	FULL_DIM;
Vector2 TEX_CIRCLE_LOADING_SEEK_LOC = 	CENTER_LOC;
Vector2 TEX_CIRCLE_LOADING_SEEK_DIM = 	FULL_DIM;
Vector2 TEX_EDIT_ICO_ADD_LOC = 			CENTER_LOC;
Vector2 TEX_EDIT_ICO_ADD_DIM = 			FULL_DIM;
Vector2 TEX_EDIT_ICO_DEL_LOC = 			CENTER_LOC;
Vector2 TEX_EDIT_ICO_DEL_DIM = 			FULL_DIM;
Vector2 TEX_EDIT_SHADOW_LOC = 			CENTER_LOC;
Vector2 TEX_EDIT_SHADOW_DIM = 			FULL_DIM;
Vector2 TEX_FOOTER_ICO_CIRCLE_LOC = 	CENTER_LOC;
Vector2 TEX_FOOTER_ICO_CIRCLE_DIM = 	FULL_DIM;
Vector2 TEX_FOOTER_ICO_CROSS_LOC = 		CENTER_LOC;
Vector2 TEX_FOOTER_ICO_CROSS_DIM = 		FULL_DIM;
Vector2 TEX_FOOTER_ICO_LT_LOC = 		CENTER_LOC;
Vector2 TEX_FOOTER_ICO_LT_DIM = 		FULL_DIM;
Vector2 TEX_FOOTER_ICO_RT_LOC = 		CENTER_LOC;
Vector2 TEX_FOOTER_ICO_RT_DIM = 		FULL_DIM;
Vector2 TEX_FOOTER_ICO_SQUARE_LOC = 	CENTER_LOC;
Vector2 TEX_FOOTER_ICO_SQUARE_DIM = 	FULL_DIM;
Vector2 TEX_FOOTER_ICO_TRIANGLE_LOC = 	CENTER_LOC;
Vector2 TEX_FOOTER_ICO_TRIANGLE_DIM = 	FULL_DIM;
Vector2 TEX_HEADER_DOT_LOC = 			CENTER_LOC;
Vector2 TEX_HEADER_DOT_DIM = 			FULL_DIM;
Vector2 TEX_HEADER_ICO_ABT_LOC = 		CENTER_LOC;
Vector2 TEX_HEADER_ICO_ABT_DIM = 		FULL_DIM;
Vector2 TEX_HEADER_ICO_CHT_LOC = 		CENTER_LOC;
Vector2 TEX_HEADER_ICO_CHT_DIM = 		FULL_DIM;
Vector2 TEX_HEADER_ICO_OPT_LOC = 		CENTER_LOC;
Vector2 TEX_HEADER_ICO_OPT_DIM = 		FULL_DIM;
Vector2 TEX_HEADER_ICO_XMB_LOC = 		CENTER_LOC;
Vector2 TEX_HEADER_ICO_XMB_DIM = 		FULL_DIM;
Vector2 TEX_HEADER_LINE_LOC = 			CENTER_LOC;
Vector2 TEX_HEADER_LINE_DIM = 			FULL_DIM;
Vector2 TEX_HELP_LOC = 					CENTER_LOC;
Vector2 TEX_HELP_DIM = 					FULL_DIM;
Vector2 TEX_MARK_ARROW_LOC = 			CENTER_LOC;
Vector2 TEX_MARK_ARROW_DIM = 			FULL_DIM;
Vector2 TEX_MARK_LINE_LOC = 			CENTER_LOC;
Vector2 TEX_MARK_LINE_DIM = 			FULL_DIM;
Vector2 TEX_OPT_OFF_LOC = 				CENTER_LOC;
Vector2 TEX_OPT_OFF_DIM = 				FULL_DIM;
Vector2 TEX_OPT_ON_LOC = 				CENTER_LOC;
Vector2 TEX_OPT_ON_DIM = 				FULL_DIM;
Vector2 TEX_SCROLL_BG_LOC = 			CENTER_LOC;
Vector2 TEX_SCROLL_BG_DIM = 			FULL_DIM;
Vector2 TEX_SCROLL_LOCK_LOC = 			CENTER_LOC;
Vector2 TEX_SCROLL_LOCK_DIM = 			FULL_DIM;
Vector2 TEX_TITLESCR_ICO_ABT_LOC = 		CENTER_LOC;
Vector2 TEX_TITLESCR_ICO_ABT_DIM = 		FULL_DIM;
Vector2 TEX_TITLESCR_ICO_CHT_LOC = 		CENTER_LOC;
Vector2 TEX_TITLESCR_ICO_CHT_DIM = 		FULL_DIM;
Vector2 TEX_TITLESCR_ICO_OPT_LOC = 		CENTER_LOC;
Vector2 TEX_TITLESCR_ICO_OPT_DIM = 		FULL_DIM;
Vector2 TEX_TITLESCR_ICO_XMB_LOC = 		CENTER_LOC;
Vector2 TEX_TITLESCR_ICO_XMB_DIM = 		FULL_DIM;
Vector2 TEX_TITLESCR_LOGO_LOC =			Vector2(0.5, 0.25);
Vector2 TEX_TITLESCR_LOGO_DIM =			Vector2(0.6, 0.185);
