#ifndef GLOBALS_HPP_
#define GLOBALS_HPP_

extern Image * tex_bgimg;
extern Image * tex_cheat;
extern Image * tex_circle_error_dark;
extern Image * tex_circle_error_light;
extern Image * tex_circle_loading_bg;
extern Image * tex_circle_loading_seek;
extern Image * tex_edit_ico_add;
extern Image * tex_edit_ico_del;
extern Image * tex_edit_shadow;
extern Image * tex_footer_ico_circle;
extern Image * tex_footer_ico_cross;
extern Image * tex_footer_ico_lt;
extern Image * tex_footer_ico_rt;
extern Image * tex_footer_ico_square;
extern Image * tex_footer_ico_triangle;
extern Image * tex_header_dot;
extern Image * tex_header_ico_abt;
extern Image * tex_header_ico_cht;
extern Image * tex_header_ico_opt;
extern Image * tex_header_ico_xmb;
extern Image * tex_header_line;
extern Image * tex_help;
extern Image * tex_mark_arrow;
extern Image * tex_mark_line;
extern Image * tex_opt_off;
extern Image * tex_opt_on;
extern Image * tex_scroll_bg;
extern Image * tex_scroll_lock;
extern Image * tex_titlescr_ico_abt;
extern Image * tex_titlescr_ico_cht;
extern Image * tex_titlescr_ico_opt;
extern Image * tex_titlescr_ico_xmb;
extern Image * tex_titlescr_logo;

extern Vector2 CENTER_LOC;
extern Vector2 TEX_BGIMG_LOC;
extern Vector2 TEX_BGIMG_DIM;
extern Vector2 TEX_CHEAT_LOC;
extern Vector2 TEX_CHEAT_DIM;
extern Vector2 TEX_CIRCLE_ERROR_DARK_LOC;
extern Vector2 TEX_CIRCLE_ERROR_DARK_DIM;
extern Vector2 TEX_CIRCLE_ERROR_LIGHT_LOC;
extern Vector2 TEX_CIRCLE_ERROR_LIGHT_DIM;
extern Vector2 TEX_CIRCLE_LOADING_BG_LOC;
extern Vector2 TEX_CIRCLE_LOADING_BG_DIM;
extern Vector2 TEX_CIRCLE_LOADING_SEEK_LOC;
extern Vector2 TEX_CIRCLE_LOADING_SEEK_DIM;
extern Vector2 TEX_EDIT_ICO_ADD_LOC;
extern Vector2 TEX_EDIT_ICO_ADD_DIM;
extern Vector2 TEX_EDIT_ICO_DEL_LOC;
extern Vector2 TEX_EDIT_ICO_DEL_DIM;
extern Vector2 TEX_EDIT_SHADOW_LOC;
extern Vector2 TEX_EDIT_SHADOW_DIM;
extern Vector2 TEX_FOOTER_ICO_CIRCLE_LOC;
extern Vector2 TEX_FOOTER_ICO_CIRCLE_DIM;
extern Vector2 TEX_FOOTER_ICO_CROSS_LOC;
extern Vector2 TEX_FOOTER_ICO_CROSS_DIM;
extern Vector2 TEX_FOOTER_ICO_LT_LOC;
extern Vector2 TEX_FOOTER_ICO_LT_DIM;
extern Vector2 TEX_FOOTER_ICO_RT_LOC;
extern Vector2 TEX_FOOTER_ICO_RT_DIM;
extern Vector2 TEX_FOOTER_ICO_SQUARE_LOC;
extern Vector2 TEX_FOOTER_ICO_SQUARE_DIM;
extern Vector2 TEX_FOOTER_ICO_TRIANGLE_LOC;
extern Vector2 TEX_FOOTER_ICO_TRIANGLE_DIM;
extern Vector2 TEX_HEADER_DOT_LOC;
extern Vector2 TEX_HEADER_DOT_DIM;
extern Vector2 TEX_HEADER_ICO_ABT_LOC;
extern Vector2 TEX_HEADER_ICO_ABT_DIM;
extern Vector2 TEX_HEADER_ICO_CHT_LOC;
extern Vector2 TEX_HEADER_ICO_CHT_DIM;
extern Vector2 TEX_HEADER_ICO_OPT_LOC;
extern Vector2 TEX_HEADER_ICO_OPT_DIM;
extern Vector2 TEX_HEADER_ICO_XMB_LOC;
extern Vector2 TEX_HEADER_ICO_XMB_DIM;
extern Vector2 TEX_HEADER_LINE_LOC;
extern Vector2 TEX_HEADER_LINE_DIM;
extern Vector2 TEX_HELP_LOC;
extern Vector2 TEX_HELP_DIM;
extern Vector2 TEX_MARK_ARROW_LOC;
extern Vector2 TEX_MARK_ARROW_DIM;
extern Vector2 TEX_MARK_LINE_LOC;
extern Vector2 TEX_MARK_LINE_DIM;
extern Vector2 TEX_OPT_OFF_LOC;
extern Vector2 TEX_OPT_OFF_DIM;
extern Vector2 TEX_OPT_ON_LOC;
extern Vector2 TEX_OPT_ON_DIM;
extern Vector2 TEX_SCROLL_BG_LOC;
extern Vector2 TEX_SCROLL_BG_DIM;
extern Vector2 TEX_SCROLL_LOCK_LOC;
extern Vector2 TEX_SCROLL_LOCK_DIM;
extern Vector2 TEX_TITLESCR_ICO_ABT_LOC;
extern Vector2 TEX_TITLESCR_ICO_ABT_DIM;
extern Vector2 TEX_TITLESCR_ICO_CHT_LOC;
extern Vector2 TEX_TITLESCR_ICO_CHT_DIM;
extern Vector2 TEX_TITLESCR_ICO_OPT_LOC;
extern Vector2 TEX_TITLESCR_ICO_OPT_DIM;
extern Vector2 TEX_TITLESCR_ICO_XMB_LOC;
extern Vector2 TEX_TITLESCR_ICO_XMB_DIM;
extern Vector2 TEX_TITLESCR_LOGO_LOC;
extern Vector2 TEX_TITLESCR_LOGO_DIM;


#endif /* GLOBALS_HPP_ */
